apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bgd
  namespace: managed-cluster
spec:
  destination:
    namespace: bgd
    name: managed-cluster
  source:
    path: bgd/base
    repoURL: https://github.com/gitops-examples/getting-started
    targetRevision: HEAD
  project: managed-cluster
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
